version: '3.8'

networks:
  adventures:
    driver: bridge

services:
  postgres:
    image: postgres:bullseye
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_HOST_AUTH_METHOD=md5
#      - PGDATA=/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432
#    volumes:
#      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - adventures
